import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
     <body
       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
     >
       <Navbar/>
       {children}
       <Toaster position="top-right"
     richColors
     closeButton
     toastOptions={{
       style: {
         borderRadius: "12px",
         background: "#111827", // dark background
         color: "#f9fafb",      // light text
         fontSize: "0.9rem",
       },
       className: "shadow-lg border border-gray-700",
       duration: 4000,
     }}/>
     </body>
   </html>
  </ClerkProvider>
  );
}
